### ISSUE TITLE
Working Arduino Hardware for tmp2ser-Firmware? Only Teensy?

### ISSUE THREAD

**Issue by ozett** [neophob/PixelController#86]
Hi,
i tried to build another matrix and wanted to connect it to my pcduino, where pixelcontroller can run 24/7. For my test I took some of my arduinos, (an itead iboard=ducemilia, an arduino-pro-mini-with328, an saintsmart-arduino uno, an arduino leonardo)  and tried it with my ws2811 and ws2801 strips and pixelcontroller running on win7 with ftdi-usb-serial/CP210x ---> with no great success. 
i used the tmp2ser firmware from the integration-subdir.
Only with the Leonardo with the 2811-strips showed some response.
if i took the example-sketch from the fast-spi library, everthing runs fine, even the ws2801 on the pro-mini. Here they dont have to get serial input, but the cabling of the strips shows up correct.

What options do i have to connect a larger Strip/matrix to usb-ports? Can i only use a teensy (2.0/3.0/3.1) with serialsupport without latency? Is it only serial-latency on the arduinos that they dont show any output to the strips? Or is there something i do wrong - or can check? another firmware? some other working configurations?

best regards,
toz

**Comment by ozett** [comment]
go here for other hardware like esp8266 (wifi) board (<2EUR):
https://github.com/neophob/PixelController/issues/75

**Comment by madmanth** [comment]
Hello Ozett!  Funny little thread of you talking yourself through the problems!  I've run into an identical issue it seems.  So the answer is to use a Teensy, or were you ever able to get this running on an UNO?  I tried to flash to a Teensy LC and get nothing out.

**Comment by ozett** [comment]
Whats exactly your issue?
Long time ago, my writings. I got lots of different setups working...

**Comment by madmanth** [comment]
Ooo I was trying to get the Ardiuno Uno to be driven from PixelController.
The Uno seems to be driving the WS2811 chip alright after futzing with some
libraries, but I only get the rainbow effect and it never latches onto the
serial signal. The Uno's tx and rx lights flash like mad in response to
pixel controller, but I just get the rainbow pattern on the led. Hopefully
it's the serial bus speed issue. I have a teensy 2.0 ordered that should be
in Monday. Looks like there's a prebuilt library in the teensy world. I had
a teensy LC, but cooked it by hooking it to a 12v rail on accident :/ oh
well!

Thanks,
Tony
