### ISSUE TITLE
Featurerequest: Change Visual #1/2 in GUI with a click 

### ISSUE THREAD

**Issue by ozett** [neophob/PixelController#92]
Why is the active/deative Sign for visual 1/2 not clickable.
the editbox seems to be. Would be nice to change with one click, wouldnt it?
i put a screenshot here to show the point on the gui 
![pixelcon](https://cloud.githubusercontent.com/assets/5937811/5792955/09a696ee-9f31-11e4-8948-8b257dfaf25e.png)

**Comment by neophob** [comment]
green = visual is used for the output, red = unused

**Comment by ozett** [comment]
i think you re-opened it, because you realized i meant: CLICK it, to switch activation. 
the existing Sign/color-funktion seems clear (to me). but has no click-funktion in v2.1.0rc2

so as i first thought not only the red or green dot could be clickable, but the whole visual could be clickable to switch activation of visual 1 or 2 would be nice. Maybe you think so, too.

cheers.
ozett

**Comment by neophob** [comment]
whoops, no i don't want to reopen it. if the visual is visible on the output depends on the current settings - it make's no sense to make it clickable.
