### ISSUE TITLE
Teensy 3.0 or 3.1 ??

### ISSUE THREAD

**Issue by rolandg** [neophob/PixelController#95]
Which of these controllers do you recommend?
Some other pixel-controlling software says you have to use 3.0.
Waht about your software?
Will it run on both?
Thanks

**Comment by neophob** [comment]
hey rolandg - the current firmware supports only teensy 2.0 (or the plus). however it shouln't be too hard to adapt it for teensy 3.0. you need to replace the whole timing in the firmware.
