### ISSUE TITLE
arduino + LPD6803 dont work

### ISSUE THREAD

**Issue by mortenx** [neophob/PixelController#97]
pixelcontrollesr 2.0 https://code.google.com/p/pixelcontroller/downloads/list  ->
arduino + LPD6803 dont work, rainbow effect is shown but no data from pixelcontroller soft... but arduino TXRX leds are flashing if pixelcontroller soft is running... but only rainbow effect in led panel..

pixelcontroller 2.1 https://github.com/neophob/PixelController/releases/tag/v2.1.0-RC1
is better
something is working  on the panels only if
output.resolution.x=8
output.resolution.y=8

 some colours are doing something but not correct from pixelcontroller soft, speed button seems to be  correct, brightness button is doing some colour change whole panel..

**Comment by neophob** [comment]
What kind of Arduino do you use?

**Comment by mortenx** [comment]
Uno and mega

**Comment by neophob** [comment]
see https://github.com/neophob/PixelController/blob/master/README.md#which-firmware-should-i-use

**Comment by mortenx** [comment]
yes but
 ...integration/ArduinoFw/pixelinvaders/neoLedLPD6803Spi

files are different in  pixelcontrollesr 2.0 and 2.1 package folder
